config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'dashboard#index'

  resources :bookings
  resources :clients
  resources :users
  resources :owners
  resources :vendors
  resources :locations
  resources :mappings
  resources :lisps
  resources :groups
  resources :subgroups
  resources :assessments
  resources :uploads

  resources :bookings do
    member do
      get 'approve'
      get 'cancel'
      get 'reject'
      get 'accept'
      get 'invoice'
      get 'details_invoice'
    end
    collection do
      post 'find_by_date_and_center'
    end
  end

  resources :sessions do
    collection do
      get 'forgot_password'
    end
  end

  resources :users do
    member do
      get 'add_operator'
      get 'update_password'
    end
  end

  resources :users do
    collection do
      post 'check_if_employee_exists'
    end
  end 

  resources :locations do
    collection do
      post 'check_if_location_exists'
    end
  end

  resources :lisps do
    collection do
      post 'check_if_lisp_exists'
    end
  end 

  
  get 'cities/:state', to: 'application#cities'
  get 'operators/:vendor_id', to: 'application#operators'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :client
  belongs_to :subgroup

  def authenticate(val)
    self.encrypted_password == val
  end

  def is_owner?
    self.role_type == "owner"
  end

  def is_admin?
    self.role_type == "admin"
  end

  def is_spoc?
    self.role_type == "spoc"
  end

  def is_approver?
    self.role_type == "approver"
  end

  def is_vendor?
    self.role_type == "vendor"
  end

  def is_admin_or_owner?
    is_admin? or is_owner?
  end

  def operators
    Operator.where(:vendor_id => id)
  end

  def email_body
      body = "<html> User #{self.name} :"
      body += "<a href='http://generator.innovatiview.com'>http://generator.innovatiview.com</a>"
      body += "<br> Email - #{self.email}"
      body += "<br> Password - #{self.encrypted_password}"
      body += "</html>"
   end

  def notify
    begin
      RestClient.post "https://api:key-ad59eb535febe7c7ff00bc1b64bf2b25"\
        "@api.mailgun.net/v3/iv-genset.com/messages",
        :from => "Innovatiview <info@innovatiview.com>",
        :to => self.email,
        :subject => "Genset account created",
        :html => email_body
      Rails.logger.info "Emailed sent to user #{self.name} successfully"
    rescue => e
      Rails.logger.error "There was an error in sending email to #{self.email} for booking - #{self.name} due to #{e}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    users = nil
    if params[:role_type] == "admin"
      users = User.where(:role_type => "admin")
    elsif params[:role_type] == "spoc"
      users = User.where(:role_type => "spoc")
    elsif params[:role_type] == "vendor"
      users = User.where(:role_type => "vendor")
    elsif params[:role_type] == "approver"
      users = User.where(:role_type => "approver")
    elsif params[:role_type] == "employee"
      users = User.where(:role_type => "employee")
    else
      users = User.where(:role_type => "owner")
    end

    if !params[:client_id].blank?
      users = users.where(:client_id => params[:client_id])
    end
    users.includes(:subgroup)
    render json: users.to_json(include: :subgroup), status: 201 
  end

  def new
    @user = User.new 
  end



  def create
    begin
      existing_user = User.find_by_email(params[:user][:email])
      if existing_user.present?
        render json: e.message, status: 500
        return
      end
      if params[:user][:employee_id].present?
        existing_user = User.find_by_employee_id(params[:user][:employee_id])
        if existing_user.present?
          redirect_to "/users/#{@user.id}", :flash => {:notice => "User already exists with this employee id"}
          return 
        end
      end

      @user = User.new(params.require(:user).permit(:name,:location,:email,
        :phone_number,:role_type,:state,:city, :employee_id, :approver_type))

      @user.role_type = @user.role_type.downcase
      @user.encrypted_password = (0...8).map { (65 + rand(26)).chr }.join
      if !params[:user][:client_id].blank?
        @user.client = Client.find(params[:user][:client_id])
      end
      if params[:user][:subgroup_id].present?
        @user.subgroup = Subgroup.find(params[:user][:subgroup_id])
      end

      @user.save
      redirect_to "/users/#{@user.id}", :flash => {:notice => "Successfully created user"}
      
    rescue => error
      render json: "Unable to create employee as email id or employee id exists already", status: 500
      return
    end
    
  end

  def show
    @user = User.find(params[:id])
    if @user.client.present?
      @subgroups = Subgroup.where(:client_id => @user.client.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update!(params.require(:user).permit(:name, :email, :phone_number, 
      :encrypted_password, :employee_id, :role_type, :subgroup_id,
      :approver_type))
    Rails.logger.info("Is Approver = #{@user.is_approver?}")
    if !@user.is_approver?
      Rails.logger.info("Not Approver = #{@user.is_approver?}")
      @user.approver_type = nil
      @user.save
    end
    if @user.client.present?
      redirect_to "/clients/#{@user.client.id}#users", :flash => {:notice => "Successfully updated user"}
    else
      redirect_to "/users/#{@user.id}", :flash => {:notice => "Successfully updated user"}
    end
  end


  def add_operator
    @user = User.find(params[:id])
    Operator.create(:name => params[:name],
      :phone_number => params[:phone_number],
      :vendor_id => @user.id
    )
    render json: {}, status: 200
  end

  def update_password
    @user = User.find(params[:id])
    @user.encrypted_password = params[:password]
    @user.save
    render json: {}, status: 200

  end

  def check_if_employee_exists
    existing_user = User.find_by_email(params[:user][:email])
      if existing_user.present?
        render json: "User already exists with this email", status: 500
        return
      end
      if params[:user][:employee_id].present?
        existing_user = User.find_by_employee_id(params[:user][:employee_id])
        if existing_user.present?
          render json: "User already exists with this employee id", status: 500
          return 
        end
      end
    render json: {}, status: 201 
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_content.html.erb
<div>
  <%= render "users/modal" %>
</div>
<div class="row users_content">
    <div>
        <% if current_user.is_admin_or_owner? %>
            <button type="button" class="btn btn-primary create-booking" data-toggle="modal" data-target="#createUser">
                Add Employee
            </button>
        <% end %>
    </div>
    

    <div class="row">
		<%= render "users/table.html.erb" %>
    </div>

</div>

<script type="text/javascript">
    $("#users").on('click', 'tr', function(){
        id = $(this).data('id')
        if(id) {
            window.location = '/users/' + id;
        }
    })

    $('#users').DataTable()

    $('#save_user').click(function(event){
        event.preventDefault();
        checkIfemployeeExists();
        $('#userForm').find('input[type=submit]').click()
    });

    $('#userForm').on('submit', function(event) {
        event.preventDefault();

        if(!$("#userForm")[0].checkValidity() || $("#user_name").val() == "" || 
            $("#user_phone_number").val() == "" || $('#role_type').val() == "" ||
            $('#user_employee_id').val() == ""
          ) {
          $("#user_form_error").show()
          return
        }
        $("#save_user").show()
        $("#save_user_loading").show()
      formData = {
        user: {
            name: $('#user_name').val(),
            email: $('#user_email').val(),
            phone_number: $('#user_phone_number').val(),
            role_type: $('#role_type').val(),
            client_id: clientId,
            employee_id: $('#user_employee_id').val(),
            subgroup_id: $('#user_subgroup_id').val(),
            approver_type: $("#approver_type").val()
        }
      }   
      $.post({
        url: '/users',
        data: formData}).done(function(data){
            alert("user created Successfully");
        location.reload()
      }).fail(function(data){
        alert(data.error().responseText);
      });
  });


</script>

app/views/users/_edit.html.erb
<%= form_for @user do |f| %>
    <div class="booking-edit panel panel-default">
        <div class="panel-heading"> User Details </div>
        <div class="panel-body">

        <table class="table table-horizontal table-bordered table-striped">
            <tbody>
            <tr>
                <th>
                    <%= f.label :name %>
                </th>
                <td>
                    <%= f.text_field(:name, :class => "form-control", :required =>true) %>
                </td>
            </tr>

            <tr>
                <th><%= f.label :email %></th>
                <td><%= f.email_field(:email, :class => "form-control", :required =>true) %></td>
            </tr>
            <tr>
                <th><%= f.label :phone_number %></th>
                <td><%= f.number_field(:phone_number, :class => "form-control", :required =>true) %></td>
            </tr>
            <tr id="role_row">
              <th><%= f.label :Role %></th>
              <td>
                <% if current_user.is_owner? %>
                <%= f.select(:role_type, ['owner', 'vendor', 'admin', 'approver', 'spoc', 'employee']) %>
                <%else%>
                <%= f.select(:role_type, ['admin', 'approver', 'spoc', 'employee']) %>
                <%end%>
              </td>
            </tr>
            <% if current_user.is_admin_or_owner? %>
            <tr id="approver_row">
              <th><%= f.label :approver_type %></th>
              <td>
                <%= f.select(:approver_type, ['NOM', 'ZOM']) %>
              </td>
            </tr>
            <%end%>
            <tr>
                <th><%= f.label :password %></th>
                <td>
                  <%= f.text_field(:encrypted_password, :class => "form-control", :required =>true) %>
                </td>
            </tr>

            <% if @user.client.present? %>
              <tr>
                <th><%= f.label :client %></th>
                <td>
                  <%= @user.client.name %>
                </td>
              </tr>
            <%end%>

            <% if @user.subgroup.present? %>
                <tr>
                    <th>
                        Subgroup
                    </th>
                    <td>
                        <%= @user.subgroup.name %>
                    </td>
                </tr>
            <%end%>
            <% if @subgroups.present? %>
            <tr>
                <th>
                    Change Subgroup
                </th>
                <td>
                    <select name="user[subgroup_id]"  class="selectdd" id="subgroup_group_id">
                        <option selected disabled>Change Subgroup</option>
                        <% @subgroups.each do |subgroup| %>
                            <option value=<%=subgroup.id%> > <%=subgroup.name%> </option>
                        <% end %>
                    </select>
                </td>
            </tr>
            <%end%>
            <tr>
                <th><label>Employee Id</label></th>
                 <td><%= f.number_field(:employee_id, :class => "form-control",:readonly => true) %></td>
            </tr>

            </tbody>
        </table>
        <% if current_user.is_admin_or_owner? %>
            <%= f.submit 'Update' %>

        <%end%>
      </div>
    </div>
<% end %>

<% if current_user.is_owner? %>
    <script type="text/javascript">
        window.is_owner= true;
    </script>
<% end %>
<script type="text/javascript">
    $(".selectdd").select2()

    $("#role_row").on('change', 'select', function(){
        if ($(this).val() == "approver" && !window.is_owner) {
            $("#approver_row").show()
        } else {
            $("#approver_row").hide()
        }
        if( window.is_owner)
        {
            alert("You cannot change your role as you are the owner");
            $(this).val("owner");
        }
    })

    <% if !@user.is_approver? %>
        $("#approver_row").hide()
    <%end%>


</script>

app/views/users/_modal.html.erb
<div class="modal fade" id="createUser" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add new User</h4>
      </div>
      <div class="modal-body">
        <form id="userForm">
        <div class="form-group">
          <label for="name">Name <span class="red">*</span></label>
          <input required type="text" class="form-control" id="user_name" pattern="[a-zA-Z0-9 ]+" oninvalid="setCustomValidity('No Special Characters are allowed in Name')" oninput="try{setCustomValidity('')}catch(e){}">
        </div>
        <div class="form-group">
          <label for="name">Phone number(10 digits) <span class="red">*</span></label>
          <input required maxlength="10" pattern="[0-9]{10}" class="form-control" id="user_phone_number">
        </div>
        <div class="form-group">
          <label for="location">Email <span class="red">*</span></label>
          <input required type="email" type="text" class="form-control" id="user_email">
        </div>

        <div class="form-group">
          <label for="location">Employee Id <span class="red">*</span></label>
          <input required type="number" class="form-control" id="user_employee_id">
        </div>

        <div class="form-group">
          <label for="sel1">Select User Type <span class="red">*</span></label>
          <select class="form-control" id="role_type">
            <option>Employee</option>
            <option>Admin</option>
            <option>SPOC</option>
            <option>Approver</option>
          </select>
        </div>

        <div class="form-group" id="approver_type_select">
          <label for="sel1">Select Approver Type <span class="red">*</span></label>
          <select class="form-control" id="approver_type">
            <option>NOM</option>
            <option>ZOM</option>
          </select>
        </div>

        <div class="form-group" id="subgroup_select">
            <label for="sel1">Subgroup</label>
            <select  class="selectdd" id="user_subgroup_id">
            <option selected disabled>Select Subgroup</option>
            <% @subgroups.each do |subgroup| %>
              <option value=<%=subgroup.id%> > <%=subgroup.name%> </option>
            <% end %>
            </select>
        </div>
        <input class="formSubmit" type="submit"></input>
        </form>
      </div>
      <div class="modal-footer">
        <div id="user_form_error" class="alert-danger">
          Please fill the required fields
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="save_user">Submit</button>
        <span class="glyphicon glyphicon-refresh spinning loading" id="save_user_loading"></span>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
  $(".selectdd").select2();
  $("#role_type").change(function(){
    if($("#role_type").val() == "SPOC") {
      $("#subgroup_select").show()
    } else {
      $("#subgroup_select").hide()
    }
    if($("#role_type").val() == "Approver") {
      $("#approver_type_select").show()
    } else {
      $("#approver_type_select").hide()
    }
  })
  $("#subgroup_select").hide()
   $("#save_user").show()
  $("#approver_type_select").hide()


  function checkIfemployeeExists()
  {
        formData = {
            user: {
                name : $('#user_name').val(),
                employee_id: $('#user_employee_id').val(),
                role_type : $('#role_type').val(),
                email: $('#user_email').val()
            }
         };
        $.post({
            url: '/users/check_if_employee_exists',
            data: formData
          }).done(function(data){
              $("#save_user").show()
          }).fail(function(data){
              $("#save_user").show()
          });
      }

</script>

app/views/users/_non_edit.html.erb
<%= form_for @user do |f| %>
    <div class="booking-edit panel panel-default">
        <div class="panel-heading"> User Details </div>
        <div class="panel-body">

        <table class="table table-horizontal table-bordered table-striped">
            <tbody>
            <tr>
                <th>
                    <%= f.label :name %>
                </th>
                <td>
                    <%= @user.name %>
                </td>
            </tr>

            <tr>
                <th><%= f.label :email %></th>
                <td><%= @user.email %></td>
            </tr>
            <tr>
                <th><%= f.label :phone_number %></th>
                <td><%= @user.phone_number %></td>
            </tr>
            <% if current_user.id == @user.id %>
            <tr>

                <th><%= f.label :password %></th>
                <td>
                  <%= @user.encrypted_password %>
                </td>
            </tr>
            <%end%>

            <% if current_user.client.present? %>
              <tr>
                <th><%= f.label :client %></th>
                <td>
                  <%= @user.client.name %>
                </td>
              </tr>
            <%end%>

            <tr>
                <th><label>Role</label></th>
                <td><%= @user.role_type %></td>
            </tr>

            <tr>
                <th><label>Approver Type</label></th>
                <td><%= @user.approver_type %></td>
            </tr>

            <tr>
                <th><label>Employee ID</label></th>
                <td><%= @user.employee_id %></td>
            </tr>

            </tbody>
        </table>
        </div>
    </div>
<% end %>

app/views/users/_table.html.erb
<table id="users" class="table hover table-bordered table-striped" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Employee Id</th>
            <th>Email</th>
            <th>Phone number</th>
            <th>Role Type</th>
            <th>Subgroup</th>
        </tr>
    </thead>
    <tbody>
        <% @employees.each do |user| %>
          <tr onclick="window.location='/users/' + <%=user.id%>">
            <td><%= user.name %></td>
            <td><%= user.employee_id %></td>
            <td><%= user.email %></td>
            <td><%= user.phone_number %></td>
            <td>
                <% if user.role_type == "approver" %>
                    <%= user.role_type %> , <%= user.approver_type %>
                <%else %>
                    <%= user.role_type %>
                <%end%>
            </td>
            <td>
                <%if user.subgroup.present?%>
                    <%= user.subgroup.name %>
                <%end%>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>

app/views/users/index.html.erb
<div id="create-modal">
    <%= render "users/modal.html.erb" %>
</div>

<div class="container main-content">

    <%= render "content.html.erb" %>

</div>

app/views/users/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user.client.present? and @user.client.id != current_user.client.id %>
  Invalid access
<%else%>

<div>
<button class="booking-edit back-btn btn btn-primary glyphicon glyphicon-arrow-left"></button>
</div>

<div class="container main-content">
  <% if current_user.is_admin_or_owner? %>
    <%= render 'edit.html.erb' %>
  <% else %>
    <%= render 'non_edit.html.erb' %>
  <% end %>

  <% if @user.is_vendor? %>
    <div class="booking-edit panel panel-default">
      <div class="panel-heading"> Operators </div>
          <div class="panel-body">
            <table class="table table-striped table-bordered booking_update" cellspacing="0" >
            <thead>
            <tr>
            <th>Name</th>
            <th>Phone number</th>
            </tr>
            </thead>
            <% @user.operators.each do |op| %>
              <tr>
                <td><%= op.name %></td>
                <td><%= op.phone_number %></td>
              </tr>
            <%end%>
            </table>

          <h4> Add new operator </h4>
          <label>Name</label>
          <input id="op_name"></input>
          <br>
          <label>Phone number</label>
          <input id="op_phone_number"></input>
          <br>
          <button id="add_op">Add</button>
        </div>
      </div>
    </div>
  <%end%>

</div>

<%end%>

<script type="text/javascript">
    $("#add_op").click(function(){
      $.ajax({
        url: '/users/' + <%= @user.id %> + '/add_operator',
        data: {
          name: $("#op_name").val(),
          phone_number: $("#op_phone_number").val()
        }
      }).done(function(){
        location.reload()
      })
    })

    $("#update_password").click(function () {
      $.ajax({
        url: '/users/' + <%= @user.id %> + '/update_password',
        data: {
          password: $("#password").val()
        }
      }).done(function(){
        location.reload()
      })
    });

     $("form").on('submit', function(event){
        if(!confirm("Are you sure you want to update user info ?")) {
            event.preventDefault();
        }
    })

     $(".back-btn").click(function(){
        history.back()
    })

</script>