config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'dashboard#index'

  resources :bookings
  resources :clients
  resources :users
  resources :owners
  resources :vendors
  resources :locations
  resources :mappings
  resources :lisps
  resources :groups
  resources :subgroups
  resources :assessments
  resources :uploads

  resources :bookings do
    member do
      get 'approve'
      get 'cancel'
      get 'reject'
      get 'accept'
      get 'invoice'
      get 'details_invoice'
    end
    collection do
      post 'find_by_date_and_center'
    end
  end

  resources :sessions do
    collection do
      get 'forgot_password'
    end
  end

  resources :users do
    member do
      get 'add_operator'
      get 'update_password'
    end
  end

  resources :users do
    collection do
      post 'check_if_employee_exists'
    end
  end 

  resources :locations do
    collection do
      post 'check_if_location_exists'
    end
  end

  resources :lisps do
    collection do
      post 'check_if_lisp_exists'
    end
  end 

  
  get 'cities/:state', to: 'application#cities'
  get 'operators/:vendor_id', to: 'application#operators'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  def index
    @client_id = params[:client_id]
    @spocs = User.where(:client_id => @client_id, :role_type => "spoc").collect {|p| [p.name, p.id]}
    @mappings = SpocToApproverMapping.all
    @approvers = User.where(:client_id => params[:client_id], :role_type => "approver").collect {|p| [p.name, p.id]}
  end

  def create
    map = SpocToApproverMapping.find_by_spoc_id(params[:user][:id])
    if map.nil?
      map = SpocToApproverMapping.create(:spoc_id => params[:user][:id],
        :approver1_id => params[:approver1][:id],
        :approver2_id => params[:approver2][:id])
    else
      map.approver1_id = params[:approver1][:id]
      map.approver2_id = params[:approver2][:id]
      map.save
    end
    redirect_to "/mappings?client_id=#{params[:current_client_id].first.first}"
  end
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/views/mappings/index.html.erb
<div class="container main-content">

    <div class="row">
    	<h3>Update Mapping</h3>
    	<%= form_for :spoc_to_approver_mapping , url: mappings_path do |f| %>
			<label>Spoc</label>
			<%= select(:user, :id, @spocs, :prompt => "Select Spoc" ) %>
			<label>Approver1</label>
			<%= select(:approver1, :id, @approvers, :prompt => "Select Approver" ) %>
			<label>Approver2</label>
			<%= select(:approver2, :id, @approvers,:prompt => "Select Approver" ) %>
			<%= hidden_field(:current_client_id, @client_id) %>
			<%= f.submit(:value => 'Save') %>
		<%end%>
    </div>

    <div class="row">
    	<h3> Current Mappings </h3>
		<table class="table hover table-bordered" cellspacing="0" width="100%">                         
		  <thead>
	        <tr>
	        	<th>Id</th>
	            <th>Spoc</th>
	            <th>Approver1</th>
	            <th>Approver2</th>
	        </tr>
		  </thead>
			<% @mappings.each do |mapping| %>
			  <tr>
			  	<td><%= mapping.id %></td>
			    <td><%= mapping.spoc.name %></td>
			    <td><%= mapping.approver1.name %></td>
			    <td><%= mapping.approver2.name %></td>
			  </tr>
			<% end %>
		</table> 
    </div>

</div>